# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits_md', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
